# Example Site settings
title: Abhiraj Mengade # name of the site
author: Abhiraj Mengade # name of site's author
email: abhiraj.mengade@outlook.com # email of site's author
url: https://abhiraj-mengade.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Abhiraj Mengade - Founder of Skyllai, Co-founder of MontaQ Labs, and former MTS at Oracle.

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - about.md
 - _pages/projects.md
 - blog.md
 - contact.md

footer: ''

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
